# Generated by Django 4.2.7 on 2023-11-09 07:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('view', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('done', 'done')], default='to_do', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=15)),
                ('deadline', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('tag', models.CharField(max_length=15)),
                ('assigner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigners', to='todo.customuser')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task2task', to='todo.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desciption_change', models.TextField()),
                ('time', models.DateTimeField()),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.task')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='my_files')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.task')),
            ],
        ),
    ]
