# Generated by Django 4.2.7 on 2023-11-09 10:39

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(blank=True, upload_to=todo.models.File.nameFile),
        ),
    ]
