# Generated by Django 4.2.7 on 2023-11-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
