# Generated by Django 4.2.7 on 2023-11-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_author_task_assigner_task_creator_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='desc_change',
            new_name='Desciption_change',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
    ]
